// Generated by Grafana k6 Studio (1.8.0) on 2025-11-29T19:51:28.719Z

import { group, sleep, check } from "k6";
import http from "k6/http";
import execution from "k6/execution";

export const options = {
  stages: [
    { target: 20, duration: "1m" },
    { target: 20, duration: "1m30s" },
    { target: 0, duration: "1m" },
  ],
};

export default function () {
  let params;
  let resp;
  let match;
  let regex;
  let url;
  const correlation_vars = {};

  group("Home", function () {
    params = {
      headers: {
        "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        "upgrade-insecure-requests": `1`,
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-user": `?1`,
        "sec-fetch-dest": `document`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=0, i`,
      },
      cookies: {},
    };

    url = http.url`https://alojando.duckdns.org/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://alojando.duckdns.org/`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://alojando.duckdns.org/api/properties`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        pragma: `no-cache`,
        "cache-control": `no-cache`,
        accept: `*/*`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://alojando.duckdns.org/sw.js`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://alojando.duckdns.org/index.html`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
  group("Login", function () {
    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
        "content-type": `application/json`,
        "sec-ch-ua-mobile": `?0`,
        origin: `https://alojando.duckdns.org`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://alojando.duckdns.org/login`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://alojando.duckdns.org/api/auth/login`;
    resp = http.request(
      "POST",
      url,
      `{"email":"sam@gmail.com","password":"samI@SuareZ0"}`,
      params,
    );

    check(resp, { "status equals 401": (r) => r.status === 401 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
        "content-type": `application/json`,
        "sec-ch-ua-mobile": `?0`,
        origin: `https://alojando.duckdns.org`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://alojando.duckdns.org/login`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://alojando.duckdns.org/api/auth/login`;
    resp = http.request(
      "POST",
      url,
      `{"email":"sami@gmail.com","password":"samI@SuareZ0"}`,
      params,
    );

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        authorization: `Bearer eyJraWQiOiJiZGM1ZDRmMy00ZTU1LTQ1OTAtYmIzZi1mZGJlOWFmOTVmYTgiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzYW1pQGdtYWlsLmNvbSIsImlzcyI6ImFsb2phbmRvLWJhY2tlbmQiLCJleHAiOjE3NjQ0NDcxMzQsImlhdCI6MTc2NDQ0NTMzNCwidXNlcklkIjoxNiwiYXV0aG9yaXRpZXMiOlsiVklTSVRBTlRFIl0sImVtYWlsIjoic2FtaUBnbWFpbC5jb20ifQ.ha6bYJIFL2c2iEtvTOsTaB2QGTLzajnRbqNiFXqz3pMI2I0_tgjgfkXsKreIAodvaAcz-caPse4-s_K5hqJpyQeZKPrgmlPBH9xeBR3TwNizA6Svp9YWuCcanL_aQVNrh6LwKL-_4ZtByPpt5L8dwpeZiQBZXCyB65ERq9C95l2VBPrjHvCu_h1tDqInekznjVJmnZFKjQ4L_S3Cm9exsSQ7OiChj7zSt33XoZQewpDazM0MRLdn9uoPTLpTGamgHicjQ2L5ACicCebg_waTb8lKAIKHi7wL7CtHtNqzyPiI2X6Gq9xpzJUmLfq3JNjvb4vFmyAp0-2Ii5PLYYu2CA`,
        accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://alojando.duckdns.org/user-dashboard/reservation`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://alojando.duckdns.org/api/bookings/me`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        authorization: `Bearer eyJraWQiOiJiZGM1ZDRmMy00ZTU1LTQ1OTAtYmIzZi1mZGJlOWFmOTVmYTgiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzYW1pQGdtYWlsLmNvbSIsImlzcyI6ImFsb2phbmRvLWJhY2tlbmQiLCJleHAiOjE3NjQ0NDcxMzQsImlhdCI6MTc2NDQ0NTMzNCwidXNlcklkIjoxNiwiYXV0aG9yaXRpZXMiOlsiVklTSVRBTlRFIl0sImVtYWlsIjoic2FtaUBnbWFpbC5jb20ifQ.ha6bYJIFL2c2iEtvTOsTaB2QGTLzajnRbqNiFXqz3pMI2I0_tgjgfkXsKreIAodvaAcz-caPse4-s_K5hqJpyQeZKPrgmlPBH9xeBR3TwNizA6Svp9YWuCcanL_aQVNrh6LwKL-_4ZtByPpt5L8dwpeZiQBZXCyB65ERq9C95l2VBPrjHvCu_h1tDqInekznjVJmnZFKjQ4L_S3Cm9exsSQ7OiChj7zSt33XoZQewpDazM0MRLdn9uoPTLpTGamgHicjQ2L5ACicCebg_waTb8lKAIKHi7wL7CtHtNqzyPiI2X6Gq9xpzJUmLfq3JNjvb4vFmyAp0-2Ii5PLYYu2CA`,
        accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://alojando.duckdns.org/user-dashboard/reservation`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://alojando.duckdns.org/api/properties`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        authorization: `Bearer eyJraWQiOiJiZGM1ZDRmMy00ZTU1LTQ1OTAtYmIzZi1mZGJlOWFmOTVmYTgiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzYW1pQGdtYWlsLmNvbSIsImlzcyI6ImFsb2phbmRvLWJhY2tlbmQiLCJleHAiOjE3NjQ0NDcxMzQsImlhdCI6MTc2NDQ0NTMzNCwidXNlcklkIjoxNiwiYXV0aG9yaXRpZXMiOlsiVklTSVRBTlRFIl0sImVtYWlsIjoic2FtaUBnbWFpbC5jb20ifQ.ha6bYJIFL2c2iEtvTOsTaB2QGTLzajnRbqNiFXqz3pMI2I0_tgjgfkXsKreIAodvaAcz-caPse4-s_K5hqJpyQeZKPrgmlPBH9xeBR3TwNizA6Svp9YWuCcanL_aQVNrh6LwKL-_4ZtByPpt5L8dwpeZiQBZXCyB65ERq9C95l2VBPrjHvCu_h1tDqInekznjVJmnZFKjQ4L_S3Cm9exsSQ7OiChj7zSt33XoZQewpDazM0MRLdn9uoPTLpTGamgHicjQ2L5ACicCebg_waTb8lKAIKHi7wL7CtHtNqzyPiI2X6Gq9xpzJUmLfq3JNjvb4vFmyAp0-2Ii5PLYYu2CA`,
        accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://alojando.duckdns.org/user-dashboard/reservation`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://alojando.duckdns.org/api/bookings/me`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        authorization: `Bearer eyJraWQiOiJiZGM1ZDRmMy00ZTU1LTQ1OTAtYmIzZi1mZGJlOWFmOTVmYTgiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzYW1pQGdtYWlsLmNvbSIsImlzcyI6ImFsb2phbmRvLWJhY2tlbmQiLCJleHAiOjE3NjQ0NDcxMzQsImlhdCI6MTc2NDQ0NTMzNCwidXNlcklkIjoxNiwiYXV0aG9yaXRpZXMiOlsiVklTSVRBTlRFIl0sImVtYWlsIjoic2FtaUBnbWFpbC5jb20ifQ.ha6bYJIFL2c2iEtvTOsTaB2QGTLzajnRbqNiFXqz3pMI2I0_tgjgfkXsKreIAodvaAcz-caPse4-s_K5hqJpyQeZKPrgmlPBH9xeBR3TwNizA6Svp9YWuCcanL_aQVNrh6LwKL-_4ZtByPpt5L8dwpeZiQBZXCyB65ERq9C95l2VBPrjHvCu_h1tDqInekznjVJmnZFKjQ4L_S3Cm9exsSQ7OiChj7zSt33XoZQewpDazM0MRLdn9uoPTLpTGamgHicjQ2L5ACicCebg_waTb8lKAIKHi7wL7CtHtNqzyPiI2X6Gq9xpzJUmLfq3JNjvb4vFmyAp0-2Ii5PLYYu2CA`,
        accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://alojando.duckdns.org/user-dashboard/reservation`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://alojando.duckdns.org/api/properties`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
  group("Reservation", function () {
    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        authorization: `Bearer eyJraWQiOiJiZGM1ZDRmMy00ZTU1LTQ1OTAtYmIzZi1mZGJlOWFmOTVmYTgiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzYW1pQGdtYWlsLmNvbSIsImlzcyI6ImFsb2phbmRvLWJhY2tlbmQiLCJleHAiOjE3NjQ0NDcxMzQsImlhdCI6MTc2NDQ0NTMzNCwidXNlcklkIjoxNiwiYXV0aG9yaXRpZXMiOlsiVklTSVRBTlRFIl0sImVtYWlsIjoic2FtaUBnbWFpbC5jb20ifQ.ha6bYJIFL2c2iEtvTOsTaB2QGTLzajnRbqNiFXqz3pMI2I0_tgjgfkXsKreIAodvaAcz-caPse4-s_K5hqJpyQeZKPrgmlPBH9xeBR3TwNizA6Svp9YWuCcanL_aQVNrh6LwKL-_4ZtByPpt5L8dwpeZiQBZXCyB65ERq9C95l2VBPrjHvCu_h1tDqInekznjVJmnZFKjQ4L_S3Cm9exsSQ7OiChj7zSt33XoZQewpDazM0MRLdn9uoPTLpTGamgHicjQ2L5ACicCebg_waTb8lKAIKHi7wL7CtHtNqzyPiI2X6Gq9xpzJUmLfq3JNjvb4vFmyAp0-2Ii5PLYYu2CA`,
        accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://alojando.duckdns.org/`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://alojando.duckdns.org/api/properties`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        authorization: `Bearer eyJraWQiOiJiZGM1ZDRmMy00ZTU1LTQ1OTAtYmIzZi1mZGJlOWFmOTVmYTgiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzYW1pQGdtYWlsLmNvbSIsImlzcyI6ImFsb2phbmRvLWJhY2tlbmQiLCJleHAiOjE3NjQ0NDcxMzQsImlhdCI6MTc2NDQ0NTMzNCwidXNlcklkIjoxNiwiYXV0aG9yaXRpZXMiOlsiVklTSVRBTlRFIl0sImVtYWlsIjoic2FtaUBnbWFpbC5jb20ifQ.ha6bYJIFL2c2iEtvTOsTaB2QGTLzajnRbqNiFXqz3pMI2I0_tgjgfkXsKreIAodvaAcz-caPse4-s_K5hqJpyQeZKPrgmlPBH9xeBR3TwNizA6Svp9YWuCcanL_aQVNrh6LwKL-_4ZtByPpt5L8dwpeZiQBZXCyB65ERq9C95l2VBPrjHvCu_h1tDqInekznjVJmnZFKjQ4L_S3Cm9exsSQ7OiChj7zSt33XoZQewpDazM0MRLdn9uoPTLpTGamgHicjQ2L5ACicCebg_waTb8lKAIKHi7wL7CtHtNqzyPiI2X6Gq9xpzJUmLfq3JNjvb4vFmyAp0-2Ii5PLYYu2CA`,
        accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://alojando.duckdns.org/propiedad/3`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://alojando.duckdns.org/api/properties/3`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        authorization: `Bearer eyJraWQiOiJiZGM1ZDRmMy00ZTU1LTQ1OTAtYmIzZi1mZGJlOWFmOTVmYTgiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzYW1pQGdtYWlsLmNvbSIsImlzcyI6ImFsb2phbmRvLWJhY2tlbmQiLCJleHAiOjE3NjQ0NDcxMzQsImlhdCI6MTc2NDQ0NTMzNCwidXNlcklkIjoxNiwiYXV0aG9yaXRpZXMiOlsiVklTSVRBTlRFIl0sImVtYWlsIjoic2FtaUBnbWFpbC5jb20ifQ.ha6bYJIFL2c2iEtvTOsTaB2QGTLzajnRbqNiFXqz3pMI2I0_tgjgfkXsKreIAodvaAcz-caPse4-s_K5hqJpyQeZKPrgmlPBH9xeBR3TwNizA6Svp9YWuCcanL_aQVNrh6LwKL-_4ZtByPpt5L8dwpeZiQBZXCyB65ERq9C95l2VBPrjHvCu_h1tDqInekznjVJmnZFKjQ4L_S3Cm9exsSQ7OiChj7zSt33XoZQewpDazM0MRLdn9uoPTLpTGamgHicjQ2L5ACicCebg_waTb8lKAIKHi7wL7CtHtNqzyPiI2X6Gq9xpzJUmLfq3JNjvb4vFmyAp0-2Ii5PLYYu2CA`,
        accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://alojando.duckdns.org/propiedad/3`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://alojando.duckdns.org/api/bookings/me`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        authorization: `Bearer eyJraWQiOiJiZGM1ZDRmMy00ZTU1LTQ1OTAtYmIzZi1mZGJlOWFmOTVmYTgiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzYW1pQGdtYWlsLmNvbSIsImlzcyI6ImFsb2phbmRvLWJhY2tlbmQiLCJleHAiOjE3NjQ0NDcxMzQsImlhdCI6MTc2NDQ0NTMzNCwidXNlcklkIjoxNiwiYXV0aG9yaXRpZXMiOlsiVklTSVRBTlRFIl0sImVtYWlsIjoic2FtaUBnbWFpbC5jb20ifQ.ha6bYJIFL2c2iEtvTOsTaB2QGTLzajnRbqNiFXqz3pMI2I0_tgjgfkXsKreIAodvaAcz-caPse4-s_K5hqJpyQeZKPrgmlPBH9xeBR3TwNizA6Svp9YWuCcanL_aQVNrh6LwKL-_4ZtByPpt5L8dwpeZiQBZXCyB65ERq9C95l2VBPrjHvCu_h1tDqInekznjVJmnZFKjQ4L_S3Cm9exsSQ7OiChj7zSt33XoZQewpDazM0MRLdn9uoPTLpTGamgHicjQ2L5ACicCebg_waTb8lKAIKHi7wL7CtHtNqzyPiI2X6Gq9xpzJUmLfq3JNjvb4vFmyAp0-2Ii5PLYYu2CA`,
        accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://alojando.duckdns.org/propiedad/3`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://alojando.duckdns.org/api/bookings/search`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        authorization: `Bearer eyJraWQiOiJiZGM1ZDRmMy00ZTU1LTQ1OTAtYmIzZi1mZGJlOWFmOTVmYTgiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzYW1pQGdtYWlsLmNvbSIsImlzcyI6ImFsb2phbmRvLWJhY2tlbmQiLCJleHAiOjE3NjQ0NDcxMzQsImlhdCI6MTc2NDQ0NTMzNCwidXNlcklkIjoxNiwiYXV0aG9yaXRpZXMiOlsiVklTSVRBTlRFIl0sImVtYWlsIjoic2FtaUBnbWFpbC5jb20ifQ.ha6bYJIFL2c2iEtvTOsTaB2QGTLzajnRbqNiFXqz3pMI2I0_tgjgfkXsKreIAodvaAcz-caPse4-s_K5hqJpyQeZKPrgmlPBH9xeBR3TwNizA6Svp9YWuCcanL_aQVNrh6LwKL-_4ZtByPpt5L8dwpeZiQBZXCyB65ERq9C95l2VBPrjHvCu_h1tDqInekznjVJmnZFKjQ4L_S3Cm9exsSQ7OiChj7zSt33XoZQewpDazM0MRLdn9uoPTLpTGamgHicjQ2L5ACicCebg_waTb8lKAIKHi7wL7CtHtNqzyPiI2X6Gq9xpzJUmLfq3JNjvb4vFmyAp0-2Ii5PLYYu2CA`,
        accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
        "content-type": `application/json`,
        "sec-ch-ua-mobile": `?0`,
        origin: `https://alojando.duckdns.org`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://alojando.duckdns.org/propiedad/3`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://alojando.duckdns.org/api/bookings`;
    resp = http.request(
      "POST",
      url,
      `{"propertyId":3,"startDate":"2025-11-30","endDate":"2025-12-01","status":"Pendiente"}`,
      params,
    );

    check(resp, { "status equals 201": (r) => r.status === 201 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        authorization: `Bearer eyJraWQiOiJiZGM1ZDRmMy00ZTU1LTQ1OTAtYmIzZi1mZGJlOWFmOTVmYTgiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzYW1pQGdtYWlsLmNvbSIsImlzcyI6ImFsb2phbmRvLWJhY2tlbmQiLCJleHAiOjE3NjQ0NDcxMzQsImlhdCI6MTc2NDQ0NTMzNCwidXNlcklkIjoxNiwiYXV0aG9yaXRpZXMiOlsiVklTSVRBTlRFIl0sImVtYWlsIjoic2FtaUBnbWFpbC5jb20ifQ.ha6bYJIFL2c2iEtvTOsTaB2QGTLzajnRbqNiFXqz3pMI2I0_tgjgfkXsKreIAodvaAcz-caPse4-s_K5hqJpyQeZKPrgmlPBH9xeBR3TwNizA6Svp9YWuCcanL_aQVNrh6LwKL-_4ZtByPpt5L8dwpeZiQBZXCyB65ERq9C95l2VBPrjHvCu_h1tDqInekznjVJmnZFKjQ4L_S3Cm9exsSQ7OiChj7zSt33XoZQewpDazM0MRLdn9uoPTLpTGamgHicjQ2L5ACicCebg_waTb8lKAIKHi7wL7CtHtNqzyPiI2X6Gq9xpzJUmLfq3JNjvb4vFmyAp0-2Ii5PLYYu2CA`,
        accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://alojando.duckdns.org/user-dashboard/reservation`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://alojando.duckdns.org/api/bookings/me`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        authorization: `Bearer eyJraWQiOiJiZGM1ZDRmMy00ZTU1LTQ1OTAtYmIzZi1mZGJlOWFmOTVmYTgiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzYW1pQGdtYWlsLmNvbSIsImlzcyI6ImFsb2phbmRvLWJhY2tlbmQiLCJleHAiOjE3NjQ0NDcxMzQsImlhdCI6MTc2NDQ0NTMzNCwidXNlcklkIjoxNiwiYXV0aG9yaXRpZXMiOlsiVklTSVRBTlRFIl0sImVtYWlsIjoic2FtaUBnbWFpbC5jb20ifQ.ha6bYJIFL2c2iEtvTOsTaB2QGTLzajnRbqNiFXqz3pMI2I0_tgjgfkXsKreIAodvaAcz-caPse4-s_K5hqJpyQeZKPrgmlPBH9xeBR3TwNizA6Svp9YWuCcanL_aQVNrh6LwKL-_4ZtByPpt5L8dwpeZiQBZXCyB65ERq9C95l2VBPrjHvCu_h1tDqInekznjVJmnZFKjQ4L_S3Cm9exsSQ7OiChj7zSt33XoZQewpDazM0MRLdn9uoPTLpTGamgHicjQ2L5ACicCebg_waTb8lKAIKHi7wL7CtHtNqzyPiI2X6Gq9xpzJUmLfq3JNjvb4vFmyAp0-2Ii5PLYYu2CA`,
        accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://alojando.duckdns.org/user-dashboard/reservation`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://alojando.duckdns.org/api/properties`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
  group("User profile", function () {
    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        authorization: `Bearer eyJraWQiOiJiZGM1ZDRmMy00ZTU1LTQ1OTAtYmIzZi1mZGJlOWFmOTVmYTgiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzYW1pQGdtYWlsLmNvbSIsImlzcyI6ImFsb2phbmRvLWJhY2tlbmQiLCJleHAiOjE3NjQ0NDcxMzQsImlhdCI6MTc2NDQ0NTMzNCwidXNlcklkIjoxNiwiYXV0aG9yaXRpZXMiOlsiVklTSVRBTlRFIl0sImVtYWlsIjoic2FtaUBnbWFpbC5jb20ifQ.ha6bYJIFL2c2iEtvTOsTaB2QGTLzajnRbqNiFXqz3pMI2I0_tgjgfkXsKreIAodvaAcz-caPse4-s_K5hqJpyQeZKPrgmlPBH9xeBR3TwNizA6Svp9YWuCcanL_aQVNrh6LwKL-_4ZtByPpt5L8dwpeZiQBZXCyB65ERq9C95l2VBPrjHvCu_h1tDqInekznjVJmnZFKjQ4L_S3Cm9exsSQ7OiChj7zSt33XoZQewpDazM0MRLdn9uoPTLpTGamgHicjQ2L5ACicCebg_waTb8lKAIKHi7wL7CtHtNqzyPiI2X6Gq9xpzJUmLfq3JNjvb4vFmyAp0-2Ii5PLYYu2CA`,
        accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://alojando.duckdns.org/user-dashboard/profile`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://alojando.duckdns.org/api/user-profiles/profile`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        authorization: `Bearer eyJraWQiOiJiZGM1ZDRmMy00ZTU1LTQ1OTAtYmIzZi1mZGJlOWFmOTVmYTgiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzYW1pQGdtYWlsLmNvbSIsImlzcyI6ImFsb2phbmRvLWJhY2tlbmQiLCJleHAiOjE3NjQ0NDcxMzQsImlhdCI6MTc2NDQ0NTMzNCwidXNlcklkIjoxNiwiYXV0aG9yaXRpZXMiOlsiVklTSVRBTlRFIl0sImVtYWlsIjoic2FtaUBnbWFpbC5jb20ifQ.ha6bYJIFL2c2iEtvTOsTaB2QGTLzajnRbqNiFXqz3pMI2I0_tgjgfkXsKreIAodvaAcz-caPse4-s_K5hqJpyQeZKPrgmlPBH9xeBR3TwNizA6Svp9YWuCcanL_aQVNrh6LwKL-_4ZtByPpt5L8dwpeZiQBZXCyB65ERq9C95l2VBPrjHvCu_h1tDqInekznjVJmnZFKjQ4L_S3Cm9exsSQ7OiChj7zSt33XoZQewpDazM0MRLdn9uoPTLpTGamgHicjQ2L5ACicCebg_waTb8lKAIKHi7wL7CtHtNqzyPiI2X6Gq9xpzJUmLfq3JNjvb4vFmyAp0-2Ii5PLYYu2CA`,
        accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://alojando.duckdns.org/user-dashboard/profile`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://alojando.duckdns.org/api/user-profiles/profile`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        authorization: `Bearer eyJraWQiOiJiZGM1ZDRmMy00ZTU1LTQ1OTAtYmIzZi1mZGJlOWFmOTVmYTgiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzYW1pQGdtYWlsLmNvbSIsImlzcyI6ImFsb2phbmRvLWJhY2tlbmQiLCJleHAiOjE3NjQ0NDcxMzQsImlhdCI6MTc2NDQ0NTMzNCwidXNlcklkIjoxNiwiYXV0aG9yaXRpZXMiOlsiVklTSVRBTlRFIl0sImVtYWlsIjoic2FtaUBnbWFpbC5jb20ifQ.ha6bYJIFL2c2iEtvTOsTaB2QGTLzajnRbqNiFXqz3pMI2I0_tgjgfkXsKreIAodvaAcz-caPse4-s_K5hqJpyQeZKPrgmlPBH9xeBR3TwNizA6Svp9YWuCcanL_aQVNrh6LwKL-_4ZtByPpt5L8dwpeZiQBZXCyB65ERq9C95l2VBPrjHvCu_h1tDqInekznjVJmnZFKjQ4L_S3Cm9exsSQ7OiChj7zSt33XoZQewpDazM0MRLdn9uoPTLpTGamgHicjQ2L5ACicCebg_waTb8lKAIKHi7wL7CtHtNqzyPiI2X6Gq9xpzJUmLfq3JNjvb4vFmyAp0-2Ii5PLYYu2CA`,
        accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
        "content-type": `application/json`,
        "sec-ch-ua-mobile": `?0`,
        origin: `https://alojando.duckdns.org`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://alojando.duckdns.org/user-dashboard/profile`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://alojando.duckdns.org/api/user-profiles/profile`;
    resp = http.request(
      "PUT",
      url,
      `{"id":16,"name":"Samanta","lastName":"Suarez Camacho","cellphone":"9876543345","country":"Mexico"}`,
      params,
    );

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://alojando.duckdns.org/`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://alojando.duckdns.org/api/properties`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://alojando.duckdns.org/`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://alojando.duckdns.org/api/properties`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
  group("Register", function () {
    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
        "content-type": `application/json`,
        "sec-ch-ua-mobile": `?0`,
        origin: `https://alojando.duckdns.org`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://alojando.duckdns.org/register`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://alojando.duckdns.org/api/user/register`;
    resp = http.request(
      "POST",
      url,
      `{"name":"Tania","lastName":"Morales Perez","cellphone":"3456789012","country":"Mexico","email":"tania@gmail.com","password":"taniA@PereZ0","role":"propietario"}`,
      params,
    );

    check(resp, { "status equals 201": (r) => r.status === 201 });
  });
  sleep(1);
}
