// Generated by Grafana k6 Studio (1.8.0) on 2025-10-28T17:47:07.564Z

import { group, sleep, check } from "k6";
import http from "k6/http";
import execution from "k6/execution";

export const options = {
  stages: [
    { target: 20, duration: "1m" },
    { target: 20, duration: "1m30s" },
    { target: 0, duration: "1m" },
  ],
};

export default function () {
  let params;
  let resp;
  let match;
  let regex;
  let url;
  const correlation_vars = {};

  group("Home", function () {
    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Pragma: `no-cache`,
        "Cache-Control": `no-cache`,
        "Accept-Encoding": `gzip, deflate`,
      },
      cookies: {},
    };

    url = http.url`http://clients2.google.com/time/1/current?cup2key=9:D7rUcm-7L1jDBJls7Xt_5lvcnd4QgFiHSbZOLpxAJeg&cup2hreq=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "x-ohttppublickey-fst": `true`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `no-cors`,
        "sec-fetch-dest": `empty`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        priority: `u=4, i`,
      },
      cookies: {},
    };

    url = http.url`https://safebrowsingohttpgateway.googleapis.com/v1/ohttp/hpkekeyconfig?key=AIzaSyA2KlwBX3mkFo30om9LUFYQhpqLoa_BNhE`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `no-cors`,
        "sec-fetch-dest": `empty`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=4, i`,
      },
      cookies: {},
    };

    url = http.url`https://redirector.gvt1.com/edgedl/chrome/dict/es-es-3-0.bdic`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `no-cors`,
        "sec-fetch-dest": `empty`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=4, i`,
      },
      cookies: {},
    };

    url = http.url`https://redirector.gvt1.com/edgedl/chrome/dict/es-es-3-0.bdic`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 302": (r) => r.status === 302 });

    params = {
      headers: {
        origin: `https://www.google.com`,
        "content-type": `application/x-www-form-urlencoded`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `no-cors`,
        "sec-fetch-dest": `empty`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=4, i`,
      },
      cookies: {},
    };

    url = http.url`https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumBrowser&laf=b64bin&json=standard`;
    resp = http.request("POST", url, JSON.parse(`{" ":""}`), params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `no-cors`,
        "sec-fetch-dest": `empty`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=4, i`,
      },
      cookies: {},
    };

    url = http.url`https://www.google.com/async/folae?async=_fmt:pb`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "x-goog-encode-response-if-executable": `base64`,
        "x-goog-api-key": `AIzaSyA2KlwBX3mkFo30om9LUFYQhpqLoa_BNhE`,
        "x-client-data": `CMnvygE=`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `no-cors`,
        "sec-fetch-dest": `empty`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=4, i`,
      },
      cookies: {},
    };

    url = http.url`https://content-autofill.googleapis.com/v1/pages/ChVDaHJvbWUvMTQxLjAuNzM5MC4xMjMSLgk23_u2Cm623xIFDVFzj2gSBQ0G1oUyEgUNO1zhzBIFDe7jnxIhNxKE7KyYLSgYt6nKAQ==?alt=proto`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "content-type": `application/x-protobuf`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `no-cors`,
        "sec-fetch-dest": `empty`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=4, i`,
      },
      cookies: {},
    };

    url = http.url`https://android.clients.google.com/checkin`;
    resp = http.request(
      "POST",
      url,
      params,
    );

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        authorization: `AidLogin 5515607658219992642:6173528533361172055`,
        "content-type": `application/x-www-form-urlencoded`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `no-cors`,
        "sec-fetch-dest": `empty`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=4, i`,
      },
      cookies: {},
    };

    url = http.url`https://android.clients.google.com/c2dm/register3`;
    resp = http.request(
      "POST",
      url,
      JSON.parse(
        `{"app":"com.google.android.gms","device":"5515607658219992642","sender":"745476177629"}`,
      ),
      params,
    );

    check(resp, { "status equals 429": (r) => r.status === 429 });

    params = {
      headers: {
        authorization: `AidLogin 5515607658219992642:6173528533361172055`,
        "content-type": `application/x-www-form-urlencoded`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `no-cors`,
        "sec-fetch-dest": `empty`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=4, i`,
      },
      cookies: {},
    };

    url = http.url`https://android.clients.google.com/c2dm/register3`;
    resp = http.request(
      "POST",
      url,
      JSON.parse(
        `{"app":"com.chrome.windows","X-subtype":"com.google.chrome.fcm.invalidations-245350905893","device":"5515607658219992642","scope":"GCM","X-scope":"GCM","gmsv":"141","appid":"cuIYvGov4A0","sender":"245350905893","ttl":"1209600"}`,
      ),
      params,
    );

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        authorization: `AidLogin 5515607658219992642:6173528533361172055`,
        "content-type": `application/x-www-form-urlencoded`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `no-cors`,
        "sec-fetch-dest": `empty`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=4, i`,
      },
      cookies: {},
    };

    url = http.url`https://android.clients.google.com/c2dm/register3`;
    resp = http.request(
      "POST",
      url,
      JSON.parse(
        `{"app":"com.chrome.windows","X-subtype":"com.google.chrome.fcm.invalidations-585406161706","device":"5515607658219992642","scope":"GCM","X-scope":"GCM","gmsv":"141","appid":"fY-p7RpfM20","sender":"585406161706","ttl":"1209600"}`,
      ),
      params,
    );

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
  group("Login", function () {
    params = {
      headers: {
        "x-goog-encode-response-if-executable": `base64`,
        "x-goog-api-key": `AIzaSyA2KlwBX3mkFo30om9LUFYQhpqLoa_BNhE`,
        "x-client-data": `CMnvygE=`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `no-cors`,
        "sec-fetch-dest": `empty`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=4, i`,
      },
      cookies: {},
    };

    url = http.url`https://content-autofill.googleapis.com/v1/pages/ChVDaHJvbWUvMTQxLjAuNzM5MC4xMjMSPAkYKVAkhAig-hIFDVFzj2gSBQ0G1oUyEgUNO1zhzBIFDe7jnxISBQ2DqFs9EgUNzkFMeiHl59t_ke13EBi3qcoB?alt=proto`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "x-chrome-uma-log-sha1": `248F486C7CFE094A4EBAA7C705F02FC52373EC67`,
        "x-chrome-uma-log-hmac-sha256": `GAJxOUTAx9ZIEKggpq1buRlqoohVTTrwOMn53HHQvdA=`,
        "x-chrome-uma-reportinginfo": `CAE=`,
        "content-encoding": `gzip`,
        "content-type": `application/vnd.chrome.uma`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `no-cors`,
        "sec-fetch-dest": `empty`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        priority: `u=4, i`,
      },
      cookies: {},
    };

    url = http.url`https://clientservices.googleapis.com/uma/v2`;
    resp = http.request(
      "POST",
      url,
      params,
    );

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "x-goog-api-key": `AIzaSyA2KlwBX3mkFo30om9LUFYQhpqLoa_BNhE`,
        "x-goog-ext-174067345-bin": `CgIIAg==`,
        "content-type": `application/x-protobuf`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `no-cors`,
        "sec-fetch-dest": `empty`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=4, i`,
      },
      cookies: {},
    };

    url = http.url`https://passwordsleakcheck-pa.googleapis.com/v1/leaks:lookupSingle`;
    resp = http.request(
      "POST",
      url,
      params,
    );

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
  group("Register", function () {
    params = {
      headers: {
        "x-goog-encode-response-if-executable": `base64`,
        "x-goog-api-key": `AIzaSyA2KlwBX3mkFo30om9LUFYQhpqLoa_BNhE`,
        "x-client-data": `CMnvygE=`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `no-cors`,
        "sec-fetch-dest": `empty`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=4, i`,
      },
      cookies: {},
    };

    url = http.url`https://content-autofill.googleapis.com/v1/pages/ChVDaHJvbWUvMTQxLjAuNzM5MC4xMjMSUQlh05EztOKsFhIFDVFzj2gSBQ0G1oUyEgUNO1zhzBIFDe7jnxISBQ2UVPrPEgUNT54n-BIFDSNgnnISBQ2DqFs9EgUNzkFMeiHYm3liFirb7Ri3qcoB?alt=proto`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "x-goog-api-key": `AIzaSyA2KlwBX3mkFo30om9LUFYQhpqLoa_BNhE`,
        "x-goog-ext-174067345-bin": `CgIIAg==`,
        "content-type": `application/x-protobuf`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `no-cors`,
        "sec-fetch-dest": `empty`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=4, i`,
      },
      cookies: {},
    };

    url = http.url`https://passwordsleakcheck-pa.googleapis.com/v1/leaks:lookupSingle`;
    resp = http.request(
      "POST",
      url,
      params,
    );

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "x-goog-encode-response-if-executable": `base64`,
        "x-goog-api-key": `AIzaSyA2KlwBX3mkFo30om9LUFYQhpqLoa_BNhE`,
        "x-client-data": `CMnvygE=`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `no-cors`,
        "sec-fetch-dest": `empty`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=4, i`,
      },
      cookies: {},
    };

    url = http.url`https://content-autofill.googleapis.com/v1/pages/ChVDaHJvbWUvMTQxLjAuNzM5MC4xMjMSXwkN3hBXPpjsQRIFDVFzj2gSBQ0G1oUyEgUNO1zhzBIFDe7jnxISBQ2UVPrPEgUNT54n-BIFDSNgnnISBQ2DqFs9EgUNzkFMehIFDYOoWz0SBQ3OQUx6IXAfzwQBdevIGLepygE=?alt=proto`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
  group("Reset password", function () {
    params = {
      headers: {
        "x-goog-encode-response-if-executable": `base64`,
        "x-goog-api-key": `AIzaSyA2KlwBX3mkFo30om9LUFYQhpqLoa_BNhE`,
        "x-client-data": `CMnvygE=`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `no-cors`,
        "sec-fetch-dest": `empty`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=4, i`,
      },
      cookies: {},
    };

    url = http.url`https://content-autofill.googleapis.com/v1/pages/ChVDaHJvbWUvMTQxLjAuNzM5MC4xMjMSZgmX3V_E3iYglhIFDVFzj2gSBQ0G1oUyEgUNO1zhzBIFDe7jnxISBQ2UVPrPEgUNT54n-BIFDSNgnnISBQ2DqFs9EgUNzkFMehIFDYOoWz0SBQ3OQUx6EgUNg6hbPSE6Bw0EeFLErxi3qcoB?alt=proto`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "x-goog-encode-response-if-executable": `base64`,
        "x-goog-api-key": `AIzaSyA2KlwBX3mkFo30om9LUFYQhpqLoa_BNhE`,
        "x-client-data": `CMnvygE=`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `no-cors`,
        "sec-fetch-dest": `empty`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=4, i`,
      },
      cookies: {},
    };

    url = http.url`https://content-autofill.googleapis.com/v1/pages/ChVDaHJvbWUvMTQxLjAuNzM5MC4xMjMSbQl-N3EgXL_YwhIFDVFzj2gSBQ0G1oUyEgUNO1zhzBIFDe7jnxISBQ2UVPrPEgUNT54n-BIFDSNgnnISBQ2DqFs9EgUNzkFMehIFDYOoWz0SBQ3OQUx6EgUNo4vIpBIFDXPQ_T0hg84JRFijpMEYt6nKAQ==?alt=proto`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
}
